import React from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Shield, Lock, Eye, Database, UserCheck, FileText, Server, Code } from "lucide-react";
import { motion } from "framer-motion";

const sections = [
  {
    icon: Database,
    title: "Data Collection",
    content: "We collect only the URLs you submit and the analysis results generated by our system. All data is stored locally on your machine in a JSON file format. No personal information is required or collected. Your analyzed articles remain private and under your complete control."
  },
  {
    icon: Server,
    title: "Local Processing",
    content: "All article analysis happens on your local machine. The backend server runs on localhost (your computer), and no data is transmitted to external servers or cloud services. This ensures complete privacy and data sovereignty."
  },
  {
    icon: Lock,
    title: "No External APIs",
    content: "Unlike other services, we don't use external AI APIs that would send your data to third parties. All processing - web scraping, summarization, sentiment analysis, and language detection - happens locally using open-source libraries."
  },
  {
    icon: Eye,
    title: "Data Storage",
    content: "Your analyzed articles are stored in a local JSON file (backend/data/articles.json) on your computer. You have full access to view, edit, or delete this file at any time. The data never leaves your machine unless you explicitly deploy the application to a server."
  },
  {
    icon: UserCheck,
    title: "Your Rights",
    content: "You have complete control over your data. Delete any article from the History page, or manually delete the entire articles.json file to remove all data. Since everything runs locally, you are the sole administrator of your information."
  },
  {
    icon: FileText,
    title: "No Cookies or Tracking",
    content: "We use minimal local storage only for theme preferences (dark/light mode). We do not use tracking cookies, analytics, or any monitoring tools. Your browsing behavior is never recorded or analyzed."
  },
  {
    icon: Code,
    title: "Open Source & Transparent",
    content: "This is a college project with complete source code visibility. Every line of code can be reviewed to verify that no hidden data collection or transmission occurs. The entire codebase is available for inspection."
  },
  {
    icon: Shield,
    title: "Security Measures",
    content: "Since the application runs locally, there's no network vulnerability. However, when deploying online, we recommend using HTTPS, implementing rate limiting, and securing your backend endpoints. For development/college demo purposes, local execution is the most secure option."
  }
];

const dataFlowSteps = [
  "User enters article URL in browser",
  "Frontend sends URL to local backend (localhost:5000)",
  "Backend scrapes article using Axios + Cheerio",
  "Content is analyzed using local NLP libraries",
  "Results are saved to local JSON file",
  "Frontend displays results - NO external transmission"
];

export default function Privacy() {
  return (
    <div className="min-h-screen p-6 md:p-10 bg-gradient-to-br from-slate-50 via-blue-50/30 to-indigo-50/40 dark:from-slate-950 dark:via-slate-900 dark:to-indigo-950/30">
      <div className="max-w-5xl mx-auto space-y-10 py-8">
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          className="text-center space-y-4"
        >
          <h1 className="text-4xl md:text-5xl font-bold text-slate-900 dark:text-white">
            Privacy Policy
          </h1>
          <p className="text-slate-600 dark:text-slate-400 text-xl max-w-3xl mx-auto leading-relaxed">
            Your privacy is our top priority. Here's how we protect your data.
          </p>
          <div className="inline-flex items-center gap-2 px-4 py-2 bg-emerald-100 dark:bg-emerald-900/30 text-emerald-700 dark:text-emerald-300 rounded-full text-sm font-semibold border border-emerald-200 dark:border-emerald-800">
            <Shield className="w-4 h-4" />
            Last updated: January 2024
          </div>
        </motion.div>

        {/* Commitment Card */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.2 }}
        >
          <Card className="bg-slate-50 dark:bg-slate-900/50 border-slate-200 dark:border-slate-800 shadow-xl">
            <CardContent className="p-8">
              <div className="flex items-start gap-4">
                <div className="w-12 h-12 bg-blue-600 rounded-2xl flex items-center justify-center flex-shrink-0 shadow-lg">
                  <Shield className="w-6 h-6 text-white" />
                </div>
                <div>
                  <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-3">Our Commitment</h2>
                  <p className="text-slate-700 dark:text-slate-300 leading-relaxed text-lg">
                    NewsIQ Pro is a local-first application built as a college project. Unlike commercial services, 
                    we prioritize your privacy by processing everything locally on your machine. No data is sent to 
                    external servers, no AI APIs are called with your content, and you maintain complete control over 
                    your information at all times.
                  </p>
                </div>
              </div>
            </CardContent>
          </Card>
        </motion.div>

        {/* Data Flow Diagram */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.3 }}
        >
          <Card className="bg-white dark:bg-slate-900 border-slate-200 dark:border-slate-800">
            <CardHeader>
              <CardTitle className="flex items-center gap-3 text-xl">
                <div className="w-10 h-10 bg-blue-100 dark:bg-blue-900/30 rounded-xl flex items-center justify-center">
                  <Server className="w-5 h-5 text-blue-600 dark:text-blue-400" />
                </div>
                <span className="text-slate-900 dark:text-white">Data Flow - How Your Information Moves</span>
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="space-y-3">
                {dataFlowSteps.map((step, index) => (
                  <motion.div
                    key={index}
                    initial={{ opacity: 0, x: -20 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ delay: 0.4 + index * 0.1 }}
                    className="flex items-center gap-4"
                  >
                    <div className="w-8 h-8 bg-blue-600 text-white rounded-full flex items-center justify-center font-bold text-sm flex-shrink-0">
                      {index + 1}
                    </div>
                    <p className="text-slate-700 dark:text-slate-300">{step}</p>
                  </motion.div>
                ))}
              </div>
              <div className="mt-6 p-4 bg-emerald-50 dark:bg-emerald-950/30 border border-emerald-200 dark:border-emerald-800 rounded-lg">
                <p className="text-emerald-800 dark:text-emerald-300 font-semibold text-center">
                  ✅ All processing happens on YOUR computer - No external data transmission
                </p>
              </div>
            </CardContent>
          </Card>
        </motion.div>

        {/* Privacy Sections */}
        <div className="space-y-6">
          {sections.map((section, index) => (
            <motion.div
              key={section.title}
              initial={{ opacity: 0, x: -20 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ delay: 0.5 + index * 0.1 }}
            >
              <Card className="bg-white dark:bg-slate-900 border-slate-200 dark:border-slate-800 hover:shadow-lg transition-all duration-300">
                <CardHeader>
                  <CardTitle className="flex items-center gap-3 text-xl">
                    <div className="w-10 h-10 bg-blue-100 dark:bg-blue-900/30 rounded-xl flex items-center justify-center">
                      <section.icon className="w-5 h-5 text-blue-600 dark:text-blue-400" />
                    </div>
                    <span className="text-slate-900 dark:text-white">{section.title}</span>
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-slate-600 dark:text-slate-400 leading-relaxed">
                    {section.content}
                  </p>
                </CardContent>
              </Card>
            </motion.div>
          ))}
        </div>

        {/* Data Access Card */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 1.5 }}
        >
          <Card className="bg-blue-50 dark:bg-blue-950/30 border-blue-200 dark:border-blue-800">
            <CardContent className="p-8">
              <h3 className="text-xl font-bold text-blue-900 dark:text-blue-300 mb-4">
                Where Is Your Data Stored?
              </h3>
              <div className="space-y-3 text-blue-800 dark:text-blue-400">
                <p>📂 <strong>File Location:</strong> backend/data/articles.json</p>
                <p>💾 <strong>Format:</strong> Plain JSON (human-readable)</p>
                <p>🔐 <strong>Access:</strong> Only you can read/modify this file</p>
                <p>🗑️ <strong>Deletion:</strong> Delete from History page or manually remove the file</p>
                <p>☁️ <strong>Cloud Storage:</strong> None - everything is local</p>
              </div>
            </CardContent>
          </Card>
        </motion.div>

        {/* Contact Card */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 1.6 }}
        >
          <Card className="bg-gradient-to-br from-slate-50 to-slate-100 dark:from-slate-800/50 dark:to-slate-900/50 border-slate-200 dark:border-slate-700">
            <CardContent className="p-8 space-y-4">
              <h2 className="text-2xl font-bold text-slate-900 dark:text-white">Questions or Concerns?</h2>
              <p className="text-slate-700 dark:text-slate-300 leading-relaxed text-lg">
                This is an educational college project demonstrating full-stack development and data privacy principles. 
                Since everything runs locally, your data privacy is inherently protected. For questions about the 
                implementation or to review the source code, you have complete access to all files.
              </p>
              <p className="text-sm text-slate-600 dark:text-slate-400">
                This privacy policy reflects the current local-only implementation. If you choose to deploy this 
                application to a public server, additional security measures and privacy considerations would apply.
              </p>
            </CardContent>
          </Card>
        </motion.div>
      </div>
    </div>
  );
}